name: Build pack
on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [published]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pack:
    name: Generate pack
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          path: BSP-Pack-HandsOn

      - name: Fetch tags
        if: github.event_name == 'release'
        working-directory: BSP-Pack-HandsOn
        run: |
          git fetch --tags --force

  
      - uses: actions/checkout@v4
        with:
          repository: Open-CMSIS-Pack/DFP-Pack-HandsOn
          fetch-depth: 0
          path: DFP-Pack-HandsOn

      - name: Install vcpkg
        uses: ARM-software/cmsis-actions/setup-vcpkg@v1
  
      - name: Register DFP pack
        run: |
          vcpkg-shell use cmsis-toolbox
          cpackget add DFP-Pack-HandsOn/ACME.ACME_DFP.pdsc

      # If you encounter problems with the following action, please check the documentation at:
      #  https://github.com/Open-CMSIS-Pack/gen-pack-action
      - uses: Open-CMSIS-Pack/gen-pack-action@main
        with:
          doxygen-version: none
          packchk-version: 1.4.1
          gen-pack-script: ./BSP-Pack-HandsOn/gen_pack.sh --no-preprocess
          gen-pack-output: ./output
